- hosts: localhost
  vars:
    gpgkey_list:
      - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
      - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
    group_list:
      - docker
      - libvirt
      - vboxsf
      - vboxusers

  become: yes      
  tasks:
    # REPOSITORIES
    - name: Import GPG keys into the RPM DB
      rpm_key:
        key: "{{ item }}"
      loop: "{{ gpgkey_list }}"
    - name: Install RPMFusion free repository
      package:
        name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
    - name: Install RPMFusion Non-free repository
      package:
        name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm
    - name: Add the flathub flatpak repository remote
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    # PACKAGES - Group names loosely follow submenu names in KDE's app launcher
    - name: Install Development tools
      package:
        name:
          - docker-compose
          - git
          - java-latest-openjdk-devel
          - java-latest-openjdk-javadoc
          - meld
          - moby-engine
          - npm
          - python3-devel
          - python3-ipython
          - python3-virtualenv
          - ShellCheck
          - vim
          - xdotool # Interact with X11 from shell scripts          
          - yarnpkg
    - name: Install Gaming / emulation apps
      package:
        name:
          - q4wine
          - steam
          - wine
          - winetricks
    - name: Install Graphics apps
      package:
        name:
          - flameshot
    - name: Install Hardware drivers & monitoring tools
      package:
        name:
          - dkms
          - hddtemp
          - htop          
          - iftop
          - iotop
          - kernel-devel
          - kmod-wl
          - lm_sensors
          - lshw
          - nvtop          
          - sysstat
    - name: Install Internet / networking applications
      package:
        name:
          - chromium
          - filezilla
          - finger
          - gnome-nettool
          - ktorrent
          - remmina
          - wireshark
    - name: Install Multimedia applications
      package:
        name:
          - asciinema
          - simplescreenrecorder
          - smplayer
    - name: Install System tools / apps
      package:
        name:
          - akmod-VirtualBox
          - beesu
          - clamav
          - clamav-update
          - cockpit
          - cockpit-machines
          - cockpit-selinux
          - exfatprogs
          - grsync
          - grub-customizer
          - kcron
          - ksystemlog
          - policycoreutils-gui # Selinux policy GUI
          - qemu-kvm
          - stress
          - virt-manager
          - VirtualBox
          - VirtualBox-server
    - name: Install Utilities / misc. apps
      package:
        name:
          - detox
          - gtkhash
          - hunspell-es # Spanish files for LO's spell checker
          - kate
          - keepassxc
          - krename
          - kruler
          - moreutils-parallel
          - ncdu
          - nfoview
          - papirus-icon-theme
          - ranger
          - tldr
          - unrar
    - name: Uninstall unused applications present in the KDE Spin
      package:
        name:
          - akregator
          - dragon
          - elisa-player
          - kaddressbook
          - kde-connect
          - kmahjongg
          - kmail
          - kmines
          - kmouth
          - korganizer
          - kpat
          - krdc
          - krfb
          - ktnef
          - kwrite
          - neochat
          - plasma-welcome
          - skanpage
          - spectacle
        state: absent
    - name: Autoremove unneeded packages installed as dependencies
      package:
        autoremove: yes
    # GROUPS
    - name: Ensure admin groups exist
      group:
        name: "{{ item }}"
      loop: "{{ group_list }}"
    # USERS
    - name: Add the local user to admin groups
      user:
        name: "{{ ansible_env.SUDO_USER }}"
        groups: "{{ item }}"
        append: yes
      loop: "{{ group_list }}"
    - name: Create a 2048-bit SSH key for the local user in $HOME/.ssh/id_rsa
      user:
        name: "{{ ansible_env.SUDO_USER }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
    # SERVICES
    - name: Enable Cockpit autostart
      systemd_service:
        name: cockpit.socket
        state: started
        enabled: true
